import { FurnitureItem, LayoutPreset, RoomConfig } from '../types/office';

// Standard configuration matching user's exact specification:
// ALL DOORS ARE TRANSPARENT GLASS SLIDING DOORS & FRONT WALL IS GLASS:
// 1. Entry Door (Transparent Glass Sliding Door) directly cornered 3 tiles wide (X = 12.0 to 15.0 ft)
// 2. Admin Dept (Transparent Glass Sliding Door) 4 tiles after corner, 3 tiles wide (Y = 4.0 to 7.0 ft)
// 3. IT Dept Door (Double Transparent Glass Sliding Doors) 3 tiles after corner, 7 tiles wide (Y = 3.0 to 10.0 ft)
export const DEFAULT_ROOM_CONFIG: RoomConfig = {
  widthFt: 15,
  lengthFt: 21,
  heightFt: 9.5,
  tileGridSizeFt: 1.0,
  doors: [
    {
      id: 'door_1_front',
      name: 'Entry Door (Glass Sliding Door)',
      wall: 'front',
      startFt: 12.0,
      widthFt: 3.0,
      type: 'glass_sliding',
      isSliding: true,
      description: 'Entry Door (Transparent glass sliding door) directly cornered at 3 tiles wide (X = 12.0 to 15.0 ft)',
    },
    {
      id: 'door_left_corner',
      name: 'Admin Dept (Glass Sliding Door)',
      wall: 'left',
      startFt: 4.5,
      widthFt: 3.0,
      type: 'glass_sliding',
      isSliding: true,
      description: 'Admin Dept (Transparent glass sliding door) positioned at Y = 4.5 to 7.5 ft, 3 tiles wide',
    },
    {
      id: 'door_right_double',
      name: 'IT Dept Door (Double Glass Sliding Doors)',
      wall: 'right',
      startFt: 3.0,
      widthFt: 7.0,
      type: 'double_glass',
      isSliding: true,
      description: 'IT Dept Door (Double transparent glass sliding doors) starting 3 tiles from corner and 7 tiles wide (Y = 3.0 to 10.0 ft)',
    },
  ],
  windowWall: {
    wall: 'top',
    widthFt: 15.0,
  },
};

// Alternative door layout if user swaps left/right doors (all sliding)
export const SWAPPED_ROOM_CONFIG: RoomConfig = {
  widthFt: 15,
  lengthFt: 21,
  heightFt: 9.5,
  tileGridSizeFt: 1.0,
  doors: [
    {
      id: 'door_1_front',
      name: 'Entry Door (Black Sliding Door)',
      wall: 'front',
      startFt: 5.5,
      widthFt: 4.0,
      type: 'sliding',
      isSliding: true,
      description: 'Entry Door (Black slide-open door) into central 5.6-tile walkway',
    },
    {
      id: 'door_left_double',
      name: 'IT Dept Door (Double Sliding Doors)',
      wall: 'left',
      startFt: 3.0,
      widthFt: 6.0,
      type: 'double_sliding',
      isSliding: true,
      description: 'IT Dept Door (Double sliding glass doors): spans 6 tiles after 3 tiles (Y = 3.0 to 9.0 ft)',
    },
    {
      id: 'door_right_single',
      name: 'Admin Dept (Wooden Sliding Door)',
      wall: 'right',
      startFt: 2.0,
      widthFt: 3.2,
      type: 'sliding',
      isSliding: true,
      description: 'Admin Dept (Wooden slide-open door): starts after 2 tiles (Y = 2.0 to 5.2 ft)',
    },
  ],
  windowWall: {
    wall: 'top',
    widthFt: 15.0,
  },
};

export const LAYOUT_PRESETS: LayoutPreset[] = [
  {
    id: 'corner_flower_right_double',
    name: 'Department Layout (Entry Door + Admin Dept + IT Dept)',
    subtitle: 'Entry Door (Black) · Admin Dept (Wood) · IT Dept (Double Glass)',
    concept:
      'Engineered to exact departmental specification: Entry Door (black sliding door) by the Cactus Base (X = 10.2 to 14.2 ft), Admin Dept (wooden sliding door) beside Left Flower Base (Y = 1.5 to 4.7 ft), and IT Dept Door (6-tile double sliding glass doors, Y = 3.0 to 9.0 ft). Zero tables in front of any department door concourse. Direct 5.6-tile central walkway leads straight to the 4.5×3.0 ft Big Table.',
    circulationRating: 100,
    acousticRating: 98,
    naturalLightRating: 96,
    corridorWidthFt: 5.6,
    keyBenefits: [
      'Entry Door (Black Sliding Door) positioned beside the Cactus Base and IT Dept Doors',
      'Admin Dept Door (Wooden Sliding Door) positioned beside the decorative Flower Base',
      'IT Dept Door (Double Sliding Glass Doors) spanning 6 tiles along the right wall (Y = 3.0 to 9.0 ft)',
      'Zero tables in front of any door: 10-ft clearance for IT Dept, 6.2-ft clearance for Admin Dept',
      'Direct 5.6-tile wide central highway straight from Entry Door to Big Table (4.5×3.0 ft)',
    ],
    zones: [
      {
        id: 'zone_central_highway',
        name: '5.6-Tile Central Highway',
        bounds: { x: 4.7, y: 0.5, w: 5.6, h: 16.5 },
        color: '#10b981',
        purpose: 'Direct 5.6-tile wide straight walkway connecting Entry Door directly to the Big Table.',
      },
      {
        id: 'zone_corner_main_concourse',
        name: 'Entry Door & IT Dept Concourse',
        bounds: { x: 9.8, y: 0.5, w: 5.0, h: 9.2 },
        color: '#10b981',
        purpose: '100% unobstructed 10-ft open entry concourse for Entry Door and IT Dept double doors.',
      },
      {
        id: 'zone_left_door_concourse',
        name: 'Admin Dept Door Concourse',
        bounds: { x: 0.5, y: 1.2, w: 4.2, h: 4.5 },
        color: '#10b981',
        purpose: '100% open passage for Admin Dept wooden sliding door with Flower Base.',
      },
      {
        id: 'zone_big_suite',
        name: 'Big Executive Suite',
        bounds: { x: 4.5, y: 16.5, w: 6.0, h: 4.2 },
        color: '#f59e0b',
        purpose: 'Big Table (4.5×3 ft) commanding the head of the central walkway.',
      },
    ],
    circulationPaths: [
      {
        id: 'path_central_highway',
        points: [
          [7.5, 0.5],
          [7.5, 17.0],
        ],
        label: '5.6-Tile Central Highway to Big Table',
        widthFt: 5.6,
        type: 'primary_highway',
        description: 'Direct straight path between left and right table banks leading to the Big Table',
      },
      {
        id: 'path_corner_main_entry',
        points: [
          [12.2, 0.5],
          [12.2, 6.0],
          [7.5, 6.0],
        ],
        label: 'Corner Main Door Concourse (By Cactus & Big Door)',
        widthFt: 4.0,
        type: 'primary_highway',
        description: 'Direct open entrance path from Corner Main Door into central highway',
      },
      {
        id: 'path_right_double_doors',
        points: [
          [14.5, 6.0],
          [7.5, 6.0],
        ],
        label: '100% Unobstructed 6-Tile Door Concourse',
        widthFt: 6.0,
        type: 'executive_access',
        description: 'Completely open passage from Right 6-tile double doors into the central highway',
      },
      {
        id: 'path_left_door',
        points: [
          [0.5, 3.1],
          [7.5, 3.1],
        ],
        label: 'Left Corner Door Clear Aisle',
        widthFt: 3.2,
        type: 'secondary_egress',
        description: 'Clear access from Left Corner Door with Flower Base into the central highway',
      },
    ],
    items: [
      // 1 MAIN BIG TABLE (4.5 tiles long x 3.0 tiles wide)
      {
        id: 'exec_desk_1',
        name: 'Big Executive Table',
        type: 'executive_desk',
        x: 4.5,
        y: 16.0,
        width: 4.5,
        length: 3.0,
        rotation: 0,
        label: 'Big Table (4.5 × 3.0 ft)',
        assignedRole: 'Director / Executive',
        color: '#d97706',
        material: 'walnut',
        hasChair: true,
        visitorChairs: 0,
        chairSide: 'bottom',
        hasMonitor: true,
        hasLaptop: true,
        cableTray: true,
        notes: 'Big Table (4.5 × 3.0 ft) at X:4.5, Y:16.0 ft with executive chair.',
      },

      // FLOWER BASE (Pedestal with floral arrangement beside Entry Door)
      {
        id: 'flower_base_left_corner',
        name: 'Entry Flower Base',
        type: 'plant',
        x: 10.5,
        y: 0.5,
        width: 1.0,
        length: 1.0,
        rotation: 0,
        label: 'Flower Base 🌸',
        assignedRole: 'Corner Decor',
        color: '#ec4899',
        material: 'marble' as any,
        notes: 'Decorative flower vase on pedestal base placed beside the entry sliding door.',
      },

      // FRONT WALL POD: 2 Desks (Table 1 at X:3.5, Table 2 at X:8.5, Y:1.0 ft)
      // Rotated 90° facing IT Dept (+X), chairs on left (facing desk)
      {
        id: 'staff_desk_1',
        name: 'Workstation 01 (Front)',
        type: 'staff_desk',
        x: 3.5,
        y: 1.0,
        width: 3.5,
        length: 2.0,
        rotation: 90,
        label: 'Table 1 (3.5 × 2.0 tiles)',
        assignedRole: 'Admin & Operations',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'left',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 1 (3.5 × 2.0 tiles) at X:3.5, Y:1.0 ft, rotated 90° with chair on the left.',
      },
      {
        id: 'staff_desk_2',
        name: 'Workstation 02 (Front)',
        type: 'staff_desk',
        x: 8.5,
        y: 1.0,
        width: 3.5,
        length: 2.0,
        rotation: 90,
        label: 'Table 2 (3.5 × 2.0 tiles)',
        assignedRole: 'Client Operations',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'left',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 2 (3.5 × 2.0 tiles) at X:8.5, Y:1.0 ft, rotated 90° with chair on the left.',
      },

      // LEFT BANK: 2 Desks + 2 Shelves (Y = 8.0 to 15.0 ft)
      // Shelf 1 (3×1.5 ft) against left wall + Table 3 (rotated 90°)
      {
        id: 'left_shelf_3',
        name: 'Left Wall Shelf 1',
        type: 'bookshelf',
        x: 0.2,
        y: 8.0,
        width: 1.5,
        length: 3.0,
        height: 3.0,
        rotation: 0,
        label: 'Shelf (3×1.5 ft)',
        assignedRole: 'Operations File Storage',
        color: '#78350f',
        material: 'walnut',
        notes: '3.0 ft height 3-tier archive shelf against the left wall for Table 3 (Y = 8.0).',
      },
      {
        id: 'staff_desk_3',
        name: 'Workstation 03 (Left Bank)',
        type: 'staff_desk',
        x: 3.5,
        y: 8.0,
        width: 3.5,
        length: 2.0,
        rotation: 90,
        label: 'Table 3 (3.5 × 2.0 tiles)',
        assignedRole: 'Operations Lead',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'left',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 3 (3.5 × 2.0 tiles) at X:3.5, Y:8.0 ft, rotated 90° with chair on the left.',
      },

      // Shelf 2 (3×1.5 ft) + Table 4 placed right below Table 3 (Y = 11.5 ft)
      {
        id: 'left_shelf_4',
        name: 'Left Wall Shelf 2',
        type: 'bookshelf',
        x: 0.2,
        y: 11.5,
        width: 1.5,
        length: 3.0,
        height: 3.0,
        rotation: 0,
        label: 'Shelf (3×1.5 ft)',
        assignedRole: 'Analyst File Storage',
        color: '#78350f',
        material: 'walnut',
        notes: '3.0 ft height 3-tier archive shelf against the left wall for Table 4 (Y = 11.5).',
      },
      {
        id: 'staff_desk_4',
        name: 'Workstation 04 (Left Bank)',
        type: 'staff_desk',
        x: 3.5,
        y: 11.5,
        width: 3.5,
        length: 2.0,
        rotation: 90,
        label: 'Table 4 (3.5 × 2.0 tiles)',
        assignedRole: 'Senior Analyst',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'left',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 4 (3.5 × 2.0 tiles) at X:3.5, Y:11.5 ft, rotated 90° with chair on the left.',
      },

      // RIGHT BANK: Shelf (Y:9.5) + Table 5 (Y:13.0) & Table 6 (Y:16.5)
      {
        id: 'right_shelf_1',
        name: 'Right Side Shelf',
        type: 'bookshelf',
        x: 10.5,
        y: 9.5,
        width: 1.5,
        length: 3.0,
        height: 3.0,
        rotation: 0,
        label: 'Shelf (3×1.5 ft)',
        assignedRole: 'Right Bank Storage',
        color: '#78350f',
        material: 'walnut',
        notes: '3.0 ft height 3-tier shelf placed at X:10.5, Y:9.5 ft.',
      },
      {
        id: 'staff_desk_5',
        name: 'Workstation 05 (Right Bank)',
        type: 'staff_desk',
        x: 10.5,
        y: 13.0,
        width: 3.5,
        length: 2.0,
        rotation: 270,
        label: 'Table 5 (3.5 × 2.0 tiles)',
        assignedRole: 'Systems Engineer',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'right',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 5 (3.5 × 2.0 tiles) at X:10.5, Y:13.0 ft, rotated with chair on right.',
      },
      {
        id: 'staff_desk_6',
        name: 'Workstation 06 (Right Bank)',
        type: 'staff_desk',
        x: 10.5,
        y: 16.5,
        width: 3.5,
        length: 2.0,
        rotation: 270,
        label: 'Table 6 (3.5 × 2.0 tiles)',
        assignedRole: 'Associate Designer',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        chairSide: 'right',
        hasMonitor: true,
        cableTray: true,
        notes: 'Table 6 (3.5 × 2.0 tiles) at X:10.5, Y:16.5 ft, rotated with chair on right.',
      },

      // Executive Tall Storage Shelf beside the Big Table (5 tiles length × 1.5 tiles wide × 6 tiles height)
      {
        id: 'bookshelf_1',
        name: 'Executive Tall Shelf',
        type: 'bookshelf',
        x: 0.2,
        y: 16.0,
        width: 1.5,
        length: 5.0,
        height: 6.0,
        rotation: 0,
        label: 'Big Shelf (5×1.5 ft)',
        assignedRole: 'Executive Archives',
        color: '#78350f',
        material: 'walnut',
        notes: 'Executive tall storage shelf (5.0 tiles length × 1.5 tiles wide × 6.0 tiles height) with 5 tiers placed alongside the Big Table.',
      },
      {
        id: 'plant_1',
        name: 'Window Plant',
        type: 'plant',
        x: 8.5,
        y: 19.5,
        width: 1.2,
        length: 1.2,
        rotation: 0,
        label: 'Greenery',
        assignedRole: 'Biophilic Touch',
        color: '#15803d',
        material: 'scandinavian_ash',
      },
      {
        id: 'cactus_base_corner',
        name: 'Corner Cactus Base',
        type: 'plant',
        x: 13.8,
        y: 0.35,
        width: 1.0,
        length: 1.0,
        rotation: 0,
        label: 'Cactus Base 🌵',
        assignedRole: 'Corner Decor',
        color: '#047857',
        material: 'scandinavian_ash',
        notes: 'Architectural desert cactus base in the corner beside the Main Door.',
      },
    ],
  },
  {
    id: 'deep_concourse',
    name: 'Staggered Dual-Pod & Grand Promenade',
    subtitle: '5.0-Tile Central Highway · Maximum Door Clearances',
    concept:
      'Arranges the desks in two distinct operational banks. Left tables start at Y=6.4 ft past the corner door. Right tables start at Y=10.2 ft to give a wide margin past the 6-tile double doors. A generous 5.0 to 5.6 tile promenade leads directly to the 4.5×3.0 ft Big Table.',
    circulationRating: 98,
    acousticRating: 95,
    naturalLightRating: 97,
    corridorWidthFt: 5.0,
    keyBenefits: [
      'Zero door obstruction guaranteed across all 4 doors',
      'Flower base preserved in the left corner',
      'Over 5 tiles of clear space between the two table banks',
      'Direct visual alignment from main entry to the Big Table',
      'Generous 3.2 ft pull-out chair envelope for all workstations',
    ],
    zones: [
      {
        id: 'zone_concourse',
        name: 'Central Promenade',
        bounds: { x: 4.8, y: 0.5, w: 5.4, h: 16.5 },
        color: '#10b981',
        purpose: 'Direct wide walkway to Big Table.',
      },
    ],
    circulationPaths: [
      {
        id: 'path_main_wide',
        points: [
          [7.5, 0.5],
          [7.5, 17.0],
        ],
        label: 'Grand Promenade to Big Table',
        widthFt: 5.0,
        type: 'primary_highway',
        description: 'Direct central highway leading to the Big Table',
      },
    ],
    items: [
      {
        id: 'exec_desk_2',
        name: 'Big Executive Table',
        type: 'executive_desk',
        x: 5.25,
        y: 16.5,
        width: 4.5,
        length: 3.0,
        rotation: 0,
        label: 'Big Table (4.5 × 3.0 ft)',
        assignedRole: 'Director',
        color: '#d97706',
        material: 'walnut',
        hasChair: true,
        visitorChairs: 0,
        chairSide: 'bottom',
        hasMonitor: true,
        hasLaptop: true,
        cableTray: true,
      },
      {
        id: 'flower_base_corner_2',
        name: 'Left Corner Flower Base',
        type: 'plant',
        x: 0.35,
        y: 0.35,
        width: 1.0,
        length: 1.0,
        rotation: 0,
        label: 'Flower Base 🌸',
        assignedRole: 'Corner Decor',
        color: '#ec4899',
        material: 'marble' as any,
      },
      {
        id: 'staff_desk_p1',
        name: 'Workstation 01',
        type: 'staff_desk',
        x: 1.2,
        y: 6.4,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 1 (3.5 × 2.0 ft)',
        assignedRole: 'Analyst',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_p2',
        name: 'Workstation 02',
        type: 'staff_desk',
        x: 1.2,
        y: 9.6,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 2 (3.5 × 2.0 ft)',
        assignedRole: 'Developer',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_p3',
        name: 'Workstation 03',
        type: 'staff_desk',
        x: 1.2,
        y: 12.8,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 3 (3.5 × 2.0 ft)',
        assignedRole: 'Designer',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_p4',
        name: 'Workstation 04',
        type: 'staff_desk',
        x: 10.3,
        y: 10.2,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 4 (3.5 × 2.0 ft)',
        assignedRole: 'Engineer',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_p5',
        name: 'Workstation 05',
        type: 'staff_desk',
        x: 10.3,
        y: 13.2,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 5 (3.5 × 2.0 ft)',
        assignedRole: 'Specialist',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_p6',
        name: 'Workstation 06',
        type: 'staff_desk',
        x: 10.3,
        y: 16.2,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 6 (3.5 × 2.0 ft)',
        assignedRole: 'Coordinator',
        color: '#2563eb',
        material: 'scandinavian_ash',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'bookshelf_p',
        name: 'Archive Bookcase',
        type: 'bookshelf',
        x: 0.2,
        y: 19.2,
        width: 1.0,
        length: 1.6,
        rotation: 0,
        label: 'Storage',
        assignedRole: 'Archives',
        color: '#78350f',
        material: 'walnut',
      },
      {
        id: 'plant_p1',
        name: 'Window Plant',
        type: 'plant',
        x: 13.5,
        y: 19.2,
        width: 1.2,
        length: 1.2,
        rotation: 0,
        label: 'Greenery',
        assignedRole: 'Biophilic Touch',
        color: '#15803d',
        material: 'scandinavian_ash',
      },
      {
        id: 'cactus_base_p',
        name: 'Corner Cactus Base',
        type: 'plant',
        x: 14.1,
        y: 0.35,
        width: 1.0,
        length: 1.0,
        rotation: 0,
        label: 'Cactus Base 🌵',
        assignedRole: 'Corner Decor',
        color: '#047857',
        material: 'scandinavian_ash',
      },
    ],
  },
  {
    id: 'mirrored_left_double',
    name: 'Mirrored Layout (6-Tile Double on Left)',
    subtitle: 'Alternative for Rooms with 6-Tile Double Door on Left Wall',
    concept:
      'Configured for the reverse door orientation: Left wall has 6-tile doors (Y=3 to 9 ft), Right wall has 1 door (Y=2 to 5.2 ft). Left desks start at Y=10.0 ft, Right desks start at Y=6.2 ft. 100% door clearance with 5.6-tile central walkway.',
    circulationRating: 100,
    acousticRating: 96,
    naturalLightRating: 98,
    corridorWidthFt: 5.6,
    keyBenefits: [
      'Tailored for rooms with 6-tile doors on the left wall',
      'Left desks start at Y = 10.0 ft to clear the 6-tile doors',
      'Right desks start at Y = 6.2 ft to clear the 1-door',
      'Zero table in front of any door',
      '5.6-tile central highway straight to Big Table',
    ],
    zones: [
      {
        id: 'zone_swapped_highway',
        name: 'Central Highway',
        bounds: { x: 4.7, y: 0.5, w: 5.6, h: 16.5 },
        color: '#10b981',
        purpose: '5.6-tile central highway to Big Table.',
      },
    ],
    circulationPaths: [
      {
        id: 'path_swapped_main',
        points: [
          [7.5, 0.5],
          [7.5, 17.0],
        ],
        label: '5.6-Tile Central Highway',
        widthFt: 5.6,
        type: 'primary_highway',
        description: 'Direct straight path to Big Table',
      },
    ],
    items: [
      {
        id: 'exec_desk_s',
        name: 'Big Executive Table',
        type: 'executive_desk',
        x: 5.25,
        y: 16.5,
        width: 4.5,
        length: 3.0,
        rotation: 0,
        label: 'Big Table (4.5 × 3.0 ft)',
        assignedRole: 'Director',
        color: '#d97706',
        material: 'walnut',
        hasChair: true,
        visitorChairs: 0,
        chairSide: 'bottom',
        hasMonitor: true,
        hasLaptop: true,
        cableTray: true,
      },
      // Left desks (6-tile doors on left at Y=3 to 9, so desks start at Y=10.0)
      {
        id: 'staff_desk_s1',
        name: 'Workstation 01',
        type: 'staff_desk',
        x: 1.2,
        y: 10.0,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 1 (3.5 × 2.0 ft)',
        assignedRole: 'Analyst',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_s2',
        name: 'Workstation 02',
        type: 'staff_desk',
        x: 1.2,
        y: 13.0,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 2 (3.5 × 2.0 ft)',
        assignedRole: 'Coordinator',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_s3',
        name: 'Workstation 03',
        type: 'staff_desk',
        x: 1.2,
        y: 16.0,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 3 (3.5 × 2.0 ft)',
        assignedRole: 'Lead',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      // Right desks (door on right is at Y=2 to 5.2, so desks start at Y=6.2)
      {
        id: 'staff_desk_s4',
        name: 'Workstation 04',
        type: 'staff_desk',
        x: 10.3,
        y: 6.2,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 4 (3.5 × 2.0 ft)',
        assignedRole: 'Engineer',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_s5',
        name: 'Workstation 05',
        type: 'staff_desk',
        x: 10.3,
        y: 9.4,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 5 (3.5 × 2.0 ft)',
        assignedRole: 'Specialist',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'staff_desk_s6',
        name: 'Workstation 06',
        type: 'staff_desk',
        x: 10.3,
        y: 12.6,
        width: 3.5,
        length: 2.0,
        rotation: 0,
        label: 'Table 6 (3.5 × 2.0 ft)',
        assignedRole: 'Designer',
        color: '#2563eb',
        material: 'warm_oak',
        hasChair: true,
        hasMonitor: true,
      },
      {
        id: 'bookshelf_s',
        name: 'Archive Bookcase',
        type: 'bookshelf',
        x: 0.2,
        y: 19.2,
        width: 1.0,
        length: 1.6,
        rotation: 0,
        label: 'Storage',
        assignedRole: 'Archives',
        color: '#78350f',
        material: 'walnut',
      },
      {
        id: 'plant_s1',
        name: 'Window Plant',
        type: 'plant',
        x: 13.5,
        y: 19.2,
        width: 1.2,
        length: 1.2,
        rotation: 0,
        label: 'Greenery',
        assignedRole: 'Biophilic Touch',
        color: '#15803d',
        material: 'scandinavian_ash',
      },
    ],
  },
];
